version: '3.7'
networks:
  apifort:
    external: false

services:
  postgres:
    image: postgres:14.1
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: connect-pay
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432

    networks:
      - apifort
    volumes:
      - ./data-test/pgdata:/var/lib/postgresql/data