version: '3.7'
services:
  server:
    image: payment-service
    container_name: payment-server
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload --use-colors"
    volumes:
      - ../:/app/
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/connect-pay"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    external_links:
      - postgres:postgres