"""update-config-model

Revision ID: 7c5a427fba8a
Revises: d03851d44dbb
Create Date: 2023-08-29 14:03:24.583729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c5a427fba8a'
down_revision: Union[str, None] = 'd03851d44dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrator_config', sa.Column('config_data', sa.JSON(), nullable=True))
    op.alter_column('integrator_config', 'providers',
               existing_type=postgresql.ENUM('HyperPay', 'PayPal', name='providers'),
               nullable=False)
    op.alter_column('integrator_config', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('integrator_config', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('integrator_config', 'providers',
               existing_type=postgresql.ENUM('HyperPay', 'PayPal', name='providers'),
               nullable=True)
    op.drop_column('integrator_config', 'config_data')
    # ### end Alembic commands ###
