"""integrator-conf

Revision ID: d03851d44dbb
Revises: c451aac65aa3
Create Date: 2023-08-28 10:13:33.155506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03851d44dbb'
down_revision: Union[str, None] = 'c451aac65aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrator_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('providers', sa.Enum('HyperPay', 'PayPal', name='providers'), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrator_config_id'), 'integrator_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrator_config_id'), table_name='integrator_config')
    op.drop_table('integrator_config')
    # ### end Alembic commands ###
