"""Second-migration

Revision ID: db8fbe5faea5
Revises: fc73c90a0ab6
Create Date: 2023-08-21 10:00:12.968578

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from sql.models import PaymentStatus
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8fbe5faea5'
down_revision: Union[str, None] = 'fc73c90a0ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status = postgresql.ENUM(PaymentStatus, name="status")
    payment_status.create(op.get_bind(), checkfirst=True)
    op.add_column('payment', sa.Column('status', payment_status))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status = postgresql.ENUM(PaymentStatus, name="status")
    payment_status.drop(op.get_bind())
    # ### end Alembic commands ###
